[project]
name = "data-pipeline"
version = "0.1.0"
description = "Data pipeline package for processing data in fraud detection system"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = []
