[project]
name = "kafka"
version = "0.1.0"
description = "Package that houses code to create a Kafka producer that streams live transaction data."
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "kafka-python-ng>=2.2.3",
    "polars>=1.20.0",
]
