[project]
name = "kafka-producer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "kafka-python-ng==2.2.2",
    "polars>=1.20.0",
    "pyarrow>=19.0.0",
    "pydantic-settings>=2.7.1",
    "rich>=13.9.4",
]
