name: Build and publish packages to AWS CodeArtifact
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
  
      # - name: Install the project
      #   run: uv sync --all-extras --dev
      #
      - name: Run tests
        run: make run-tests 
        continue-on-error: false

      - name: Build and publish packages
        run: make publish-packages
        continue-on-error: false
