name: Build and publish packages to AWS CodeArtifact
on:
  push:
    branches: [ main ]
    paths:
      - 'data-pipeline/**'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [data-pipeline]
    defaults:
      run:
        working-directory: ${{ matrix.package }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests 
        continue-on-error: false

      - name: Build package
        run: uv build 
        continue-on-error: false

      - name: Publish package
        run: uv publish
        continue-on-error: false
